---
- hosts: vb
  tasks:
    - ping: ~

    - name: Update APT Package Manager
      become: true
      apt:
        update_cache: yes

    - name: Upgrade
      become: true
      apt:
        upgrade: safe

    - name: Install cowsay - it's probably important
      become: yes
      apt:
        name: cowsay
